---
- name: Router
  hosts: all
  become: true

  tasks:

    - name: Turn rounting on
      lineinfile:
         path: /etc/sysctl.conf
         create: yes
         regexp: '^net.ipv4.conf.all.forwarding'
         line: 'net.ipv4.conf.all.forwarding=1'
      notify: restart network

    - name: Routing on eth1
      lineinfile:
         path: /etc/sysconfig/network-scripts/route-eth1
         create: yes
         regexp: '^192.168.0.0'
         line: '192.168.0.0/16 via 192.168.255.2 dev eth1'
      notify: restart network

    - name: Masquerade
      iptables:
         table: nat
         chain: POSTROUTING
         out_interface: eth0
         jump: MASQUERADE
         destination: '! 192.168.0.0/16'

    - name: Save 
      shell: iptables-save > /etc/sysconfig/iptables

    - name: Restore
      lineinfile:
         path: /etc/rc.local
         create: yes
         regexp: '^iptables-restore'
         line: 'iptables-restore < /etc/sysconfig/iptables'

    - name: Executable
      file:
        path: /etc/rc.d/rc.local
        mode: '+x'

#    - name: disable NM
#      service:
#        name: NetworkManager
#        enabled: no


    - name: Copy bond config
      template:
        src: ../templates/ifcfg-bond0.j2
        dest: /etc/sysconfig/network-scripts/ifcfg-bond0
        mode: 0666
      notify: restart network

    - name: Copy eth2 config
      template:
        src: ../templates/ifcfg-eth.j2
        dest: /etc/sysconfig/network-scripts/ifcfg-eth2
        mode: 0666
      vars:
        iface: 2
      notify: restart network

    - name: Copy eth3 config
      template:
        src: ../templates/ifcfg-eth.j2
        dest: /etc/sysconfig/network-scripts/ifcfg-eth3
        mode: 0666
      vars:
        iface: 3
      notify: restart network


  handlers:
    - name: restart network
      service: 
           name: network
           state: restarted



