# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {

  :Router1 => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.1.1', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "vlan1"},
                   {ip: '192.168.2.1', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "vlan2"},
                ]
  },
  :Router2 => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.1.2', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "vlan1"},
                   {ip: '192.168.3.2', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "vlan3"},
                ]
  },

  :Router3 => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.2.3', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "vlan2"},
                   {ip: '192.168.3.3', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "vlan3"},
                ]
  },
  
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s
        when "Router1"
	    box.vm.provision "ansible" do |ansible|
	        ansible.playbook = "playbooks/router.yml"
	        ansible.verbose = true
	        ansible.extra_vars = {
                    router: "192.168.1.1",
	            net1: "192.168.1.0/24",
	            net2: "192.168.2.0/24"
	        }
            end
        when "Router2"
	    box.vm.provision "ansible" do |ansible|
	        ansible.playbook = "playbooks/router.yml"
	        ansible.verbose = true
	        ansible.extra_vars = {
                    router: "192.168.1.2",
	            net1: "192.168.1.0/24",
	            net2: "192.168.3.0/24"
	        }
	    end
        when "Router3"
	    box.vm.provision "ansible" do |ansible|
	        ansible.playbook = "playbooks/router.yml"
	        ansible.verbose = true
	        ansible.extra_vars = {
                    router: "192.168.2.1",
	            net1: "192.168.2.0/24",
	            net2: "192.168.3.0/24"
	        }
	    end

        end

      end

  end
  
  
end

