- name: setup master
  hosts: all
  become: True
  gather_facts: False
  tasks:

  - name: repository
    yum:
      name: https://repo.percona.com/yum/percona-release-latest.noarch.rpm
      state: present

  - name: install mysql
    yum:
      name: Percona-Server-server-57
      state: present
    notify: restart mysql

  - name: config
    template:
        src: ../templates/my2.cnf.j2
        dest: /etc/my.cnf.d/my2.cnf
        mode: 0444

  - name: start mysql
    systemd:
      name: mysql.service
      state: restarted


  - name: get password
    shell: grep 'password is generated' /var/log/mysqld.log | awk '{print $11}' | head -1
    register: password

  - name: update password
    shell: |
      set -e
      mysql --connect-expired-password -uroot -p'{{ password.stdout }}' -e 'ALTER USER USER() IDENTIFIED BY "{{ mysql_password }}"'
    when: password.stdout


  - name: import dmp
    shell: |
      mysql -uroot -p'{{ mysql_password }}' -e 'CREATE DATABASE bets'
      mysql -uroot -p'{{ mysql_password }}' -D bets < /home/vagrant/bet.dmp


  - name: slave setup
    shell: |
      mysql -uroot -p'{{ mysql_password }}' -e 'CHANGE MASTER TO MASTER_HOST="192.168.1.1", MASTER_USER="replica", MASTER_PASSWORD="{{ mysql_password }}", MASTER_AUTO_POSITION=1;'
      mysql -uroot  -p'{{ mysql_password }}' -e 'START SLAVE;'

  handlers:
  - name: restart mysql
    systemd:
      name: mysql.service
      state: restarted
