# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {

  :master => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.1.1', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "vlan1"},
                ]
  },
  :slave => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.1.2', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "vlan1"},
                ]
  },

}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        box.vm.provision "file", source: "bet.dmp", destination: "/home/vagrant/bet.dmp"

        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s
        when "master"
	    box.vm.provision "ansible" do |ansible|
	        ansible.playbook = "playbooks/master.yml"
	        ansible.verbose = true
	        ansible.extra_vars = {
		    mysql_password: 'Mypass1!',
		    id: "1"
	        }
            end
        when "slave"
	    box.vm.provision "ansible" do |ansible|
	        ansible.playbook = "playbooks/slave.yml"
	        ansible.verbose = true
	        ansible.extra_vars = {
		    mysql_password: 'Mypass1!',
		    id: "2"
	        }
	    end

        end

      end

  end
  
  
end

