---
- name: Router
  hosts: all
  become: true

  tasks:

    - name: Turn rounting on
      lineinfile:
         path: /etc/sysctl.conf
         regexp: '^net.ipv4.conf.all.forwarding'
         line: 'net.ipv4.conf.all.forwarding=1'
      notify: restart system

    - name: Disable selinux
      selinux:
        state: disabled

    - name: Copy ifcfg tun0
      template:
        src: ../templates/ifcfg-tun0.j2
        dest: /etc/sysconfig/network-scripts/ifcfg-tun0
        mode: 0666
      notify: restart system

    - name: Copy route tun0
      template:
        src: ../templates/route-tun0.j2
        dest: /etc/sysconfig/network-scripts/route-tun0
        mode: 0666
      notify: restart system

    - name: Install epel
      yum:
        name: epel-release
        state: present

    - name: Install openvpn
      yum:
        name: openvpn
        state: present

    - name: copy certificates
      copy:
        src: ./files/client/
        dest: /etc/openvpn
        mode: 0644
        owner: root

    - name: copy script
      copy:
        src: ./start.sh
        dest: /home/vagrant
        mode: 0755
        owner: vagrant



  handlers:
    - name: restart system
      reboot:
   
