---
- name: Server
  hosts: all
  become: true

  tasks:

    - name: Install epel
      yum: 
        name: epel-release
        state: present

    - name: Install nginx
      yum: 
        name: nginx
        state: present
      notify: start nginx


  handlers:

    - name: start nginx
      service: 
        name: nginx
        state: started