
- name: Install
  yum:  name={{ item }}  state=present
  with_items:
     - php-fpm 
     - php-json
     - php-cli 
     - php-gd 
     - php-ldap 
     - php-odbc 
     - php-pdo 
     - php-pear 
     - php-xml 
     - php-xmlrpc 
     - php-mbstring 
     - php-snmp 
     - php-soap
     - unzip
 

- name: Copy fpm www.conf
  copy: src=./files/php/www.conf dest=/etc/php-fpm.d/www.conf

- name: Php-fpm restart
  systemd:
    name: php-fpm
    state: restarted
    enabled: yes

- name: Copy nginx laravel.conf
  copy: src=./files/php/laravel.conf dest=/etc/nginx/conf.d/laravel.conf

- name: Create laravel directory
  file:
    path: /var/www/laravel
    state: directory
    mode: '0755'
    owner: nginx
    group: root

- name: Install composer 
  shell: |
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer
    cd /var/www/laravel

- name: Install laravel
  command: 
    chdir: /var/www/laravel
    cmd: /usr/bin/composer -n create-project laravel/laravel . 
    creates: /var/www/laravel/.env 
 
- name: Copy php
  copy: src=./files/php/hello.php dest=/var/www/laravel/app/Http/hello.php

- name: Laravel directory owner
  file:
    path: /var/www/laravel
    state: directory
    recurse: yes
    owner: nginx
    group: nginx

- name: Laravel storage owner
  file:
    path: /var/www/laravel/storage
    state: directory
    mode: '0755'
    owner: nginx
    group: nginx
