# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :host => {
        :box_name => "centos/8",
        :ip_addr => '192.168.11.150'
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "200"]
          end
          
          box.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
            sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            systemctl restart sshd
          SHELL

      end
      config.vm.provision 'file', source: 'test_login.sh', destination: '/tmp/test_login.sh'
      config.vm.provision 'file', source: '51-docker.rules', destination: '/tmp/51-docker.rules'
      config.vm.provision 'shell', path: 'script.sh'

  end
end
