---
- name: Server
  hosts: all
  become: true

  tasks:
    - name: Turn default gateway on vagrant interfaсe off
      lineinfile:
         path: /etc/sysconfig/network-scripts/ifcfg-eth0
         regexp: '^DEFROUTE'
         line: 'DEFROUTE=no'
      notify: restart system

    - name: Turn default gateway on new interfaсe on
      lineinfile:
         path: /etc/sysconfig/network-scripts/ifcfg-eth1
         regexp: '^DEFROUTE'
         line: 'DEFROUTE=yes'
      notify: restart system

    - name: Set gateway
      lineinfile:
         path: /etc/sysconfig/network-scripts/ifcfg-eth1
         regexp: '^GATEWAY'
         line: 'GATEWAY={{ ip_gate }}'
      notify: restart system

    - name: Install epel
      yum: 
        name: epel-release
        state: present

    - name: Install nginx
      yum: 
        name: nginx
        state: present
      notify: start nginx


  handlers:
    - name: restart system
      reboot:

    - name: start nginx
      service: 
        name: nginx
        state: started