# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "vvv"
    ansible.playbook = "playbooks/playbook.yml"
    ansible.become = "true"
  end
  config.vm.network "forwarded_port", guest: 80, host: 80


  config.vm.provider "virtualbox" do |v|
    v.memory = 256
    v.cpus = 1
  end


end
