# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
:inetRouter => {
        :box_name => "centos/7",
        #:public => {:ip => '10.10.10.1', :adapter => 1},
        :net => [
                   {ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                   {adapter: 3, virtualbox__intnet: "internal-net"},
                   {adapter: 4, virtualbox__intnet: "internal-net"},
                ]
  },
  :centralRouter => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.255.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                   {ip: '192.168.0.1', adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
#                   {ip: '192.168.0.33', adapter: 4, netmask: "255.255.255.240", virtualbox__intnet: "hw-net"},
#                   {ip: '192.168.0.65', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "mgt-net"},
#                   {ip: '192.168.255.5', adapter: 6, netmask: "255.255.255.252", virtualbox__intnet: "o1-tun"},
#                   {ip: '192.168.255.9', adapter: 7, netmask: "255.255.255.252", virtualbox__intnet: "o2-tun"},
                   {adapter: 4, virtualbox__intnet: "internal-net"},
                   {adapter: 5, virtualbox__intnet: "internal-net"},
                ]
  },

  :office1Router => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.255.6', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "o1-tun"},
                   {ip: '192.168.2.1', adapter: 3, netmask: "255.255.255.192", virtualbox__intnet: "dev1-net"},
                   {ip: '192.168.2.65', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "test1-net"},
                   {ip: '192.168.2.129', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "man1-net"},
                   {ip: '192.168.2.193', adapter: 6, netmask: "255.255.255.192", virtualbox__intnet: "hw1-net"},
                ]
  },

  :office2Router => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.255.10', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "o2-tun"},
                   {ip: '192.168.1.1', adapter: 3, netmask: "255.255.255.128", virtualbox__intnet: "dev2-net"},
                   {ip: '192.168.1.129', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "test2-net"},
                   {ip: '192.168.1.193', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "hw2-net"},
                ]
  },
  
  :centralServer => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.0.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
                   {adapter: 3, auto_config: false, virtualbox__intnet: true},
                   {adapter: 4, auto_config: false, virtualbox__intnet: true},
                ]
  },

  :office1Server => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.2.66', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "test1-net"},
                ]
  },

  :office2Server => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.1.130', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "test2-net"},
                ]
  },

  :testClient1 => {
        :box_name => "centos/7",
        :net => [
                   {virtualbox__intnet: "test1-net"},
                ]
  },
  :testClient2 => {
        :box_name => "centos/7",
        :net => [
                   {virtualbox__intnet: "test1-net"},
                ]
  },
  :testServer1 => {
        :box_name => "centos/7",
        :net => [
                   {virtualbox__intnet: "test1-net"},
                ]
  },
  :testServer2 => {
        :box_name => "centos/7",
        :net => [
                   {virtualbox__intnet: "test1-net"},
                ]
  },



  
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s
        when "inetRouter"
	    box.vm.provision "ansible" do |ansible|
	        ansible.playbook = "playbooks/inet.yml"
	        ansible.verbose = true
	        ansible.extra_vars = {
	            ip_addr: "10.10.20.1"
	        }
	    end
        when "centralRouter"
	    box.vm.provision "ansible" do |ansible|
	        ansible.playbook = "playbooks/central.yml"
	        ansible.verbose = true
	        ansible.extra_vars = {
	            ip_gate: "192.168.255.1",
	            ip_addr: "10.10.20.2"
	        }
	    end
        when "office1Router"
	    box.vm.provision "ansible" do |ansible|
	        ansible.playbook = "playbooks/router.yml"
	        ansible.verbose = true
	        ansible.extra_vars = {
	            ip_gate: "192.168.255.5"
	        }
	    end
        when "office2Router"
	    box.vm.provision "ansible" do |ansible|
	        ansible.playbook = "playbooks/router.yml"
	        ansible.verbose = true
	        ansible.extra_vars = {
	            ip_gate: "192.168.255.9"
	        }
	    end
        when "centralServer"
	    box.vm.provision "ansible" do |ansible|
	        ansible.playbook = "playbooks/server.yml"
	        ansible.verbose = true
	        ansible.extra_vars = {
	            ip_gate: "192.168.0.1"
	        }
	    end
        when "office1Server"
	    box.vm.provision "ansible" do |ansible|
	        ansible.playbook = "playbooks/server.yml"
	        ansible.verbose = true
	        ansible.extra_vars = {
	            ip_gate: "192.168.2.65"
	        }
	    end
        when "office2Server"
	    box.vm.provision "ansible" do |ansible|
	        ansible.playbook = "playbooks/server.yml"
	        ansible.verbose = true
	        ansible.extra_vars = {
	            ip_gate: "192.168.1.129"
	        }
	    end
        when "testClient1"
	    box.vm.provision "ansible" do |ansible|
	        ansible.playbook = "playbooks/vlan.yml"
	        ansible.verbose = true
	        ansible.extra_vars = {
	            ip_addr: "10.10.10.254",
		    vlan: "2"
	        }
	    end
        when "testClient2"
	    box.vm.provision "ansible" do |ansible|
	        ansible.playbook = "playbooks/vlan.yml"
	        ansible.verbose = true
	        ansible.extra_vars = {
	            ip_addr: "10.10.10.254",
		    vlan: "3"
	        }
	    end
        when "testServer1"
	    box.vm.provision "ansible" do |ansible|
	        ansible.playbook = "playbooks/vlan.yml"
	        ansible.verbose = true
	        ansible.extra_vars = {
	            ip_addr: "10.10.10.1",
		    vlan: "2"
	        }
	    end
        when "testServer2"
	    box.vm.provision "ansible" do |ansible|
	        ansible.playbook = "playbooks/vlan.yml"
	        ansible.verbose = true
	        ansible.extra_vars = {
	            ip_addr: "10.10.10.1",
		    vlan: "3"
	        }
	    end
        end

      end

  end
  
  
end

