---
- name: Router
  hosts: all
  become: true

  tasks:
#    - name: Turn default gateway on vagrant interfaсe off
#      lineinfile:
#         path: /etc/sysconfig/network-scripts/ifcfg-eth0
#         regexp: '^DEFROUTE'
#         line: 'DEFROUTE=no'
#      notify: restart system

#    - name: Turn default gateway on new interfaсe on
#      lineinfile:
#         path: /etc/sysconfig/network-scripts/ifcfg-eth1
#         regexp: '^DEFROUTE'
#         line: 'DEFROUTE=yes'
#      notify: restart system

#    - name: Set gateway
#      lineinfile:
#         path: /etc/sysconfig/network-scripts/ifcfg-eth1
#         regexp: '^GATEWAY'
#         line: 'GATEWAY={{ ip_gate }}'
#      notify: restart system

    - name: Turn rounting on
      lineinfile:
         path: /etc/sysctl.conf
         regexp: '^net.ipv4.conf.all.forwarding'
         line: 'net.ipv4.conf.all.forwarding=1'
      notify: restart system


    - name: Turn asymmetric rounting on
      lineinfile:
         path: /etc/sysctl.conf
         regexp: '^net.ipv4.conf.all.rp_filter'
         line: 'net.ipv4.conf.all.rp_filter=0'
      notify: restart system

    - name: Turn asymmetric rounting on
      lineinfile:
         path: /etc/sysctl.conf
         regexp: '^net.ipv4.conf.default.rp_filter'
         line: 'net.ipv4.conf.default.rp_filter=0'
      notify: restart system

    - name: Disable selinux
      selinux:
        state: disabled

    - name: Install quagga
      yum:
        name: quagga
        state: present
 
    - name: Copy config 
      template:
        src: ../templates/ospfd.conf.j2
        dest: /etc/quagga/ospfd.conf
        mode: 0666

    - name: enable quagga
      service:
        name: zebra
        enabled: yes
      notify: start quagga 

    - name: enable ospfd
      service:
        name: ospfd
        enabled: yes
      notify: start ospfd 

    - name: Install tcpdump
      yum:
        name: tcpdump
        state: present


  handlers:
    - name: restart system
      reboot:
   
    - name: start quagga
      service:
        name: zebra
        state: started

    - name: start ospfd
      service:
        name: ospfd
        state: started
